spring.application.name=YueZhangProfile

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.hibernate.ddl-auto=update


# 核心：推迟 data.sql 的执行，直到 Hibernate 把表建好
spring.jpa.defer-datasource-initialization=true
